name: Build Kernel Redwood with KernelSU-Next (Neutron Clang 30062026)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 zstd

      - name: Download Specific Neutron Clang (Tag 30062026)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p toolchain
          cd toolchain
          gh release download 30062026 --repo Neutron-Toolchains/clang-build-catalogue --pattern "*.zst"
          tar -I zstd -xf *.zst
          rm *.zst
          curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
          chmod +x antman
          ./antman --patch=glibc

      - name: Inject KernelSU-Next (v3.3.0)
        run: |
          # Langsung inject karena kita sudah berada di root folder source kernel
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s v3.3.0

      - name: Build Kernel
        run: |
          # Hilangkan cd kernel
          export PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Scarlet-Builder"
          export KBUILD_BUILD_HOST="GitHub-Actions"

          make O=out vendor/redwood_defconfig
          
          make -j$(nproc --all) O=out \
            LLVM=1 \
            LLVM_IAS=1 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Pack with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
          # Ubah path copy image karena tidak pakai folder "kernel" lagi
          cp out/arch/arm64/boot/Image AnyKernel3/
          
          cd AnyKernel3
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' anykernel.sh
          zip -r9 ../ShinjiKernel-KSUN-redwood.zip *

      - name: Upload Kernel Artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: ShinjiKernel-KSUNext v1.0
          path: ShinjiKernel-KSUN-redwood.zip
          
